version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    groups:
      verida:
        patterns:
          - "@verida/*"
      others:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "@verida/*"
